/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#c8c6c8',
        'surface-container': '#eeeeec',
        'surface-container-highest': '#e2e3e1',
        'on-background': '#1a1c1b',
        'on-primary-fixed-variant': '#93000f',
        outline: '#926e6b',
        'surface-variant': '#e2e3e1',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'surface-tint': '#c00017',
        'outline-variant': '#e8bcb8',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#dadad8',
        background: '#f9f9f7',
        'secondary-fixed': '#e4e2e4',
        'secondary-container': '#e2dfe1',
        'surface-bright': '#f9f9f7',
        'on-tertiary-fixed-variant': '#5d4200',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdad6',
        'surface-container-high': '#e8e8e6',
        'tertiary-fixed-dim': '#f9bd3b',
        'on-secondary-fixed': '#1b1b1d',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'on-surface-variant': '#5e3f3c',
        'on-secondary-fixed-variant': '#474649',
        surface: '#f9f9f7',
        'inverse-primary': '#ffb3ac',
        primary: '#bb0016',
        'on-secondary-container': '#636264',
        tertiary: '#785600',
        'tertiary-container': '#976d00',
        'tertiary-fixed': '#ffdea6',
        'inverse-on-surface': '#f1f1ef',
        'on-primary-container': '#fffbff',
        'on-tertiary-container': '#fffbff',
        'primary-container': '#e61724',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#410003',
        'primary-fixed-dim': '#ffb3ac',
        'on-tertiary-fixed': '#271900',
        secondary: '#5f5e60',
        'on-surface': '#1a1c1b',
        'inverse-surface': '#2f3130',
        'surface-container-low': '#f4f4f2',
        charcoal: '#1C1C1E',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        'noto-serif': ['"Noto Serif"', 'serif'],
      },
      scale: {
        102: '1.02',
      },
    },
  },
  plugins: [],
}

